### ISSUE TITLE
Storing the API key

### ISSUE THREAD

**Issue by PySimpleGUI** [TheRyanMajd/img-to-ics#3]
Hiya!

Noticed you have a GUI... I didn't see a screenshot in your readme (may be a good addition at some point).

Anyway, the point is about storing API keys and the like.

There are several APIs in PySimpleGUI that help with GUI-related code such as storing of private passwords/keys.  PSG tries to simplify the application development as a whole.  "Settings" come along as a requirement for Apps, so I created an easy access to JSON files.

This demo shows a feature new to PSG 5 that adds a parameter to the elements themselves so you can include it in the layout.
https://github.com/PySimpleGUI/PySimpleGUI/blob/master/DemoPrograms/Demo_User_Settings_Element_setting_Parameter.py

There are other user settings examples in the Demo Programs.  This is a newer one with a settings window to set the API key:
https://github.com/PySimpleGUI/PySimpleGUI/blob/master/DemoPrograms/Demo_Program_Desktop_Widget_LED_Clock_Weather.py

It's how I store all my private key info for programs I release publicly or store on GitHub so that I don't accidently include my key if I release the code.

Happy building!

**Comment by TheRyanMajd** [comment]
Hi PySimpleGUI,

Thank you so much for your suggestions and the demo links! I've added a new feature to the project that incorporates your advice on safely storing API keys using the settings management in PySimpleGUI. The latest commit includes this update, and I also added a screenshot of the GUI to the readme.

Thanks again for your help!

Best,
Ryan

**Comment by PySimpleGUI** [comment]
![image](https://github.com/TheRyanMajd/img-to-ics/assets/46163555/e38be388-1970-495f-b069-f6ab5e8620d1) the screenshot!

The User Settings APIs are super handy for passwords, API keys, etc,
They stop the chances of accidently checking in a password or a key..... something I've done a time or two
![image](https://github.com/TheRyanMajd/img-to-ics/assets/46163555/b9ee3d34-95d0-4b22-ba8f-2d93660dbfac)

The reason for the new `setting` parameter that was added was in part to ensure I use the settings file as I can build it right into the layout which forces me to go that route.

Thanks for the thanks!  Happy building!
